### PR TITLE
add ability to ignore migrations

### PR DESCRIPTION
**Pull request by fbeckklaus**
While i use this package with ```tenancyforlaravel``` package i need to ignore the migrations after publishing. This feature can useful for any other to

So you can now call in your AppServiceProvider.php

```php
public function register(): void{
        ...
        Favorite::ignoreMigrations();
}
```

### CODE REVIEW

**Comment by overtrue** [comment]
Thanks for your contribution, but I can think of a simpler way to do it, which is to just remove those two lines:

https://github.com/overtrue/laravel-favorite/blob/master/src/FavoriteServiceProvider.php#L19-L21C10

Users can just publish migrations to their application's directory, or not publish them if they don't need them. What do you think?

**Comment by fbeckklaus** [comment]
Hi, sure. It can be done by removing this 2 lines. In this case you will disable „automatically migration“ for this package and  force the user to publish the migration before migrate the database, right?

**Comment by overtrue** [comment]
> Hi, sure. It can be done by removing this 2 lines. In this case you will disable „automatically migration“ for this package and force the user to publish the migration before migrate the database, right?

Yes many packages doing like that, so I think auto migration is a bad idea that I have made.

**Comment by overtrue** [comment]
Thanks for your contribution, I'm going to close this PR as it is a breaking change that will result in incompatibility with the current version. While we could release a big version to support , I think it might be the most convenient change to just disable the default migration behavior, thanks!

**Pull request closed without merging**
